# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  #schedule:
  #    - cron:  '0 4 3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
    inputs:
      default_branch:
        description: 'The base branch like development'
        required: true
        default: 'development'
      staging_branch:
        description: 'The base branch like staging/uat'
        required: true
        default: 'staging'
      release_branch:
        description: 'The base branch like release/production'
        required: true
        default: 'release'
      pull_request_reviewers:
        description: 'this can a comma seperated list and/or github team'
        required: true
        default: 'mje0002'
      pull_request_labels:
        description: 'A comma seperated list of labels'
        required: true
        default: 'automated-pr'
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: 'master'
      STAGING_BRANCH: 'staging'
      RELEASE_BRANCH: 'release'
      PULL_REQUEST_REVIEWERS: 'mje0002'
      PULL_REQUEST_LABELS: 'automated-pr'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set Env if workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "DEFAULT_BRANCH=${{github.event.inputs.default_branch}}" >> $GITHUB_ENV
          echo "STAGING_BRANCH=${{github.event.inputs.staging_branch}}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${{github.event.inputs.release_branch}}" >> $GITHUB_ENV
          echo "PULL_REQUEST_REVIEWERS=${{github.event.inputs.pull_request_reviewers}}" >> $GITHUB_ENV
          echo "PULL_REQUEST_LABELS=${{github.event.inputs.pull_request_labels}}" >> $GITHUB_ENV
          
      - run: echo "CURRENT_DATE=$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v2
        with: 
          ref: ${{env.DEFAULT_BRANCH}} ## Need to change this to your base branch
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Merge ${{env.DEFAULT_BRANCH}} to ${{env.STAGING_BRANCH}}'
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ github.ref }} ## Current Checked out Branch Master
          target_branch: '${{env.STAGING_BRANCH}}' ## Branch we wish to merge into staging
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}' 
      - name: Merge has Failed
        if: ${{ failure() }}
        run: echo "Send message to Slack about merge failure - needs manual intervention"
        
      - name: 'Checkout ${{env.STAGING_BRANCH}}'
        uses: actions/checkout@v2
        with: 
          ref: ${{env.STAGING_BRANCH}} ## Need to change this to your base branch
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Change Log
        shell: bash
        run: |
          CHANGE_LOG=$(git cherry -v origin/${{env.RELEASE_BRANCH}} | awk '$0=$2' | git log --no-walk --stdin --pretty='%Cred%h%Creset %s (%ci) %cn:<%an>')
          echo "CHANGE_LOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGE_LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: change_log
        
      - uses: actions/checkout@v2
        with:
          ref: ${{env.RELEASE_BRANCH}} ## Need to change this to your base branch
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Reset main branch, so we can PR!
        run: |
          git fetch origin ${{env.STAGING_BRANCH}}:${{env.STAGING_BRANCH}}
          git reset --hard ${{env.STAGING_BRANCH}}
      
      - name: Create Pull Request
        id: autopr
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Auto-generated per github action
            title: "Automatic Cut and Pull Request ${{env.CURRENT_DATE}}"
            body: |
              This PR is auto-generated by 
              [create-pull-request](https://github.com/peter-evans/create-pull-request).
              
              ${{env.CHANGE_LOG}}
              
            branch: 'automated-${{env.STAGING_BRANCH}}'
            delete-branch: true
            labels: '${{env.PULL_REQUEST_LABELS}}'
            reviewers: '${{env.PULL_REQUEST_REVIEWERS}}'
            
      - name: Failed to create Pull Request
        if: ${{ failure() }}
        run: echo "Send message to Slack about Pull Request"
      - name: Created Pull Request
        if: ${{ success() }}
        run: echo "Send message to Slack about Pull Request ${{ steps.autopr.outputs.pull-request-number }} - ${{ steps.autopr.outputs.pull-request-url }}"
        
      - name: Generate Jira Ticket for Pull Request to release
        run: echo "Generating JIRA ticket for PR \n ${{env.PR_DIFF}}"
      - name: Created Jira Ticket
        if: ${{ success() }}
        run: echo "Send message to Slack about Pull Request and Jira Ticket"
      - name: Failed to create Jira Ticket
        if: ${{ failure() }}
        run: echo "Send message to Slack about Pull Request and jira ticket"
