# This is a basic workflow to help you get started with Actions

name: CI Release PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with: 
          ref: staging ## Need to change this to your base branch
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check staging -> release difference
        shell: bash
        run: |
          PR_DIFF=$(git cherry -v origin/release | awk '$0=$2' | git log --no-walk --stdin --pretty='%Cred%h%Creset %s (%ci) %cn:<%an>')
          echo "PR_DIFF<<EOF" >> $GITHUB_ENV
          echo "$PR_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: extract_diff
        
      - run: echo "${{env.PR_DIFF}}"
      #- name: Create Pull Request
      #  id: autopr
      #  uses: peter-evans/create-pull-request@v3
      #  with:
      #      token: ${{ secrets.GITHUB_TOKEN }}
      #      commit-message: Auto-generated per github action
      #      title: "Automatic Cut and Pull Request ${{env.CURrENT_DATE}}"
      #      body: |
      #        This PR is auto-generated by 
      #        [create-pull-request](https://github.com/peter-evans/create-pull-request).
      #        
      #        ${{env.PR_DIFF}}
      #        
      #      branch: automated-cut
      #      delete-branch: true
      #      labels: automated pr
      #      reviewers: mje0002
            
      #- name: Failed to create Pull Request
      #  if: ${{ failure() }}
      #  run: echo "Send message to Slack about Pull Request"
      #- name: Created Pull Request
      #  if: ${{ success() }}
      #  run: echo "Send message to Slack about Pull Request ${{ steps.autopr.outputs.pull-request-number }} - ${{ steps.autopr.outputs.pull-request-url }}"
        
      #- name: Generate Jira Ticket for Pull Request to release
      #  run: echo "Generating JIRA ticket for PR \n ${{env.PR_DIFF}}"
      #- name: Created Jira Ticket
      #  if: ${{ success() }}
      #  run: echo "Send message to Slack about Pull Request and Jira Ticket"
      #- name: Failed to create Jira Ticket
      #  if: ${{ failure() }}
      #  run: echo "Send message to Slack about Pull Request"

